version: "3"

services:
  jupyter:
    build: .
    volumes:
      - .:/workspace:cached
    ports:
      - 8888:8888
    environment:
      NB_USER: "${USER}"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      CHOWN_EXTRA: "/workspace"
    user: root
