version: "3"

services:
  jupyter:
    build: .
    volumes:
      - ./src:/home/${USERNAME}/work
    ports:
      - 8888:8888
    environment:
      NB_USER: "${USERNAME}"
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      CHOWN_HOME_OPTS: "-R"
      CHOWN_EXTRA: "/home/${USERNAME}"
    user: root
    command: start-notebook.sh --NotebookApp.token ''
